flowchart LR
                A[Definitions of<br/>Economics] --> B[Wealth Definition<br/>Adam Smith]
                A --> C[Welfare Definition<br/>Alfred Marshall]
                A --> D[Scarcity Definition<br/>Lionel Robbins]
                A --> E[Growth-Oriented<br/>Definition<br/>Samuelson]