flowchart TD
                A[Scarcity of Resources] --> B[Unlimited Human Wants]
                A --> C[Limited Resources]
                A --> D[Resources Have Alternative Uses]
                B --> E[ECONOMIC PROBLEM ARISES]
                C --> E
                D --> E