flowchart LR
                A[Collection<br/>of Data] --> B[Organisation<br/>of Data]
                B --> C[Presentation<br/>of Data]
                C --> D[Analysis<br/>of Data]
                D --> E[Interpretation<br/>of Data]