flowchart TD
                A[Functions of Statistics] --> B[1. Simplifies Complex Facts]
                A --> C[2. Presents Facts in Definite Form]
                A --> D[3. Helps in Forecasting]
                A --> E[4. Formulation & Testing of Hypothesis]
                A --> F[5. Enlarges Knowledge & Experience]