flowchart TD
                A[Types of Sampling] --> B[Random Sampling<br/>Probability Sampling]
                A --> C[Non-Random Sampling<br/>Non-Probability Sampling]

                B --> D[Simple Random Sampling]
                B --> E[Restricted Random Sampling]

                E --> F[Stratified Random]
                E --> G[Systematic]
                E --> H[Cluster]
                E --> I[Multistage]

                C --> J[Judgement Sampling]
                C --> K[Quota Sampling]
                C --> L[Convenience Sampling]