flowchart TD
                A[Sources of Data] --> B[Internal Sources]
                A --> C[External Sources]
                B --> D[Data collected from within the organisation]
                C --> D2[Data collected from outside the organisation]