flowchart TD
                A[Objectives of Classification] --> B[1. Simplify & condense mass of data]
                A --> C[2. Explain similarities & dissimilarities]
                A --> D[3. Facilitate comparisons]
                A --> E[4. Study relationships between groups]
                A --> F[5. Prepare data for tabulation]
                A --> G[6. Present a mental picture of data]