flowchart TD
                A[Types of Continuous Series] --> B[Exclusive Series]
                A --> C[Inclusive Series]
                A --> D[Open-End Distribution]
                A --> E[Cumulative Frequency Series]
                A --> F[Equal & Unequal Class-Interval]
                A --> G[Mid-Value Series]