flowchart TD
                A[Methods of Classification] --> B[Geographical<br/>/Spatial]
                A --> C[Chronological<br/>/Temporal]
                A --> D[Qualitative]
                A --> E[Quantitative]
                D --> F[Simple<br/>Classification]
                D --> G[Manifold<br/>Classification]