flowchart TD
                A[Presentation of Data] --> B[1. Textual / Descriptive Presentation]
                A --> C[2. Tabular Presentation]
                A --> D[3. Diagrammatic Presentation]
                A --> E[4. Graphical Presentation]