flowchart TD
                A[Parts of a Table] --> B[1. Table Number]
                A --> C[2. Title of the Table]
                A --> D[3. Head Note]
                A --> E[4. Column Heading / Caption]
                A --> F[5. Stubs / Row Headings]
                A --> G[6. Body of the Table]
                A --> H[7. Unit of Measurement]
                A --> I[8. Footnote]
                A --> J[9. Source Note]